"""add predicted winner and confidence to outcome records

Revision ID: 8906f4fcd17b
Revises: c17e9e99571b
Create Date: 2026-08-09 18:40:32.100415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8906f4fcd17b'
down_revision: Union[str, Sequence[str], None] = 'c17e9e99571b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcomerecord', sa.Column('predicted_winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('outcomerecord', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcomerecord', 'confidence')
    op.drop_column('outcomerecord', 'predicted_winner')
    # ### end Alembic commands ###
