"""add outcome_record table

Revision ID: c17e9e99571b
Revises: 6fe4a5425df6
Create Date: 2026-08-09 13:08:32.343854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c17e9e99571b'
down_revision: Union[str, Sequence[str], None] = '6fe4a5425df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcomerecord',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actual_winner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actual_score', sa.Float(), nullable=False),
    sa.Column('accuracy_percentage', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['analysissession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomerecord')
    # ### end Alembic commands ###
